//! Contract tests for code generated by `#[derive(SyncEntity)]`.
//!
//! `KitchenSink` exercises every column type the macro supports, so the
//! suite catches regressions in the generated mapping, repository, and
//! `SyncEntity` impl without each real entity having to re-test it.

use std::collections::HashMap;

use chrono::Utc;
use dsot_db_sync::{
    DsotDatabase, RepositoryRegistry, SyncEntity, SyncEntityRepository,
    model::{JournalEntry, SyncOperation, UpdateColumnOp, UpdateValue},
    repo::ListQuery,
};
use dsot_derive::SyncEntity;
use redb::{Database, backends::InMemoryBackend};
use serde::{Deserialize, Serialize};
use sqlx::{SqlitePool, sqlite::SqlitePoolOptions};
use uuid::Uuid;

// Covers every column type currently supported by `IntoUpdateValue`
// (see src/db_sync/src/model/update_value.rs). `Vec<u8>` is intentionally
// omitted: `UpdateValue::Blob` exists but no `IntoUpdateValue for Vec<u8>`
// impl does, so the macro can't compile op_update for Blob fields yet.
#[derive(Debug, Clone, Deserialize, Serialize, Default, SyncEntity)]
#[table(kitchen_sinks)]
pub struct KitchenSink {
    pub id: Uuid,
    pub name: String,
    pub note: Option<String>,
    pub count: i64,
    pub ratio: f64,
    pub flag: bool,
    pub tags: sqlx::types::Json<Vec<String>>,
}

const SCHEMA: &str = "\
CREATE TABLE kitchen_sinks (
    id BLOB PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    note TEXT,
    count INTEGER NOT NULL,
    ratio REAL NOT NULL,
    flag INTEGER NOT NULL,
    tags TEXT NOT NULL DEFAULT '[]',
    created TEXT NOT NULL,
    updated TEXT NOT NULL,
    deleted INTEGER NOT NULL DEFAULT 0
) STRICT;
CREATE VIRTUAL TABLE kitchen_sinks_fts USING fts5(id UNINDEXED, name);
";

// max_connections(1) keeps every query on the same in-memory database;
// the default pool would give each connection its own empty `:memory:`.
async fn setup_pool() -> SqlitePool {
    let pool = SqlitePoolOptions::new()
        .max_connections(1)
        .connect("sqlite::memory:")
        .await
        .expect("connect in-memory sqlite");
    sqlx::raw_sql(SCHEMA)
        .execute(&pool)
        .await
        .expect("apply kitchen_sinks schema");
    pool
}

async fn setup_database() -> DsotDatabase {
    let pool = setup_pool().await;
    let journal = Database::builder()
        .create_with_backend(InMemoryBackend::new())
        .expect("create in-memory redb");
    DsotDatabase::new(journal, pool)
}

fn sample(name: &str) -> KitchenSinkSql {
    KitchenSinkSql {
        id: Uuid::now_v7(),
        name: name.to_string(),
        note: Some(format!("note for {name}")),
        count: 42,
        ratio: 1.5,
        flag: true,
        tags: sqlx::types::Json(vec!["a".into(), "b".into()]),
        created: Utc::now(),
        updated: Utc::now(),
        deleted: false,
    }
}

// ----- Mapping -----

#[test]
fn from_src_to_sql_sets_default_metadata() {
    let input = KitchenSink {
        id: Uuid::now_v7(),
        name: "Name".into(),
        note: Some("Note".into()),
        count: 7,
        ratio: 0.25,
        flag: true,
        tags: sqlx::types::Json(vec!["t".into()]),
    };

    let sql: KitchenSinkSql = input.clone().into();

    assert_eq!(sql.id, input.id);
    assert_eq!(sql.name, input.name);
    assert_eq!(sql.note, input.note);
    assert_eq!(sql.count, input.count);
    assert_eq!(sql.ratio, input.ratio);
    assert_eq!(sql.flag, input.flag);
    assert_eq!(sql.tags.0, input.tags.0);
    assert_eq!(sql.deleted, false);
}

#[test]
fn from_sql_to_src_copies_user_fields_and_drops_metadata() {
    let input = KitchenSinkSql {
        id: Uuid::now_v7(),
        name: "Name".into(),
        note: Some("Note".into()),
        count: 7,
        ratio: 0.25,
        flag: true,
        tags: sqlx::types::Json(vec!["t".into()]),
        created: Utc::now(),
        updated: Utc::now(),
        deleted: true,
    };

    let src: KitchenSink = input.clone().into();

    assert_eq!(src.id, input.id);
    assert_eq!(src.name, input.name);
    assert_eq!(src.note, input.note);
    assert_eq!(src.count, input.count);
    assert_eq!(src.ratio, input.ratio);
    assert_eq!(src.flag, input.flag);
    assert_eq!(src.tags.0, input.tags.0);
}

// ----- op_update -----

fn changes_by_column(op: SyncOperation) -> HashMap<String, UpdateValue> {
    match op {
        SyncOperation::Update(_, list) => list.into_iter().map(|c| (c.column, c.value)).collect(),
        other => panic!("expected SyncOperation::Update, got {other:?}"),
    }
}

#[test]
fn op_update_emits_changed_column_plus_updated_timestamp() {
    let id = Uuid::now_v7();
    let prev = KitchenSinkSql {
        id,
        name: "old".into(),
        ..KitchenSinkSql::default()
    };
    let next = KitchenSinkSql {
        name: "new".into(),
        ..prev.clone()
    };

    let by_col = changes_by_column(next.op_update(&prev).expect("changes detected"));

    assert_eq!(by_col.len(), 2);
    assert_eq!(by_col["name"], UpdateValue::Text("new".into()));
    assert!(by_col.contains_key("updated"));
}

// ----- Repository CRUD -----

#[tokio::test]
async fn insert_then_get_roundtrips_every_field() {
    let pool = setup_pool().await;
    let mut conn = pool.acquire().await.unwrap();

    let row = sample("smoke");
    let id = row.id;

    KitchenSinkSqlRepository::insert(&mut conn, &row)
        .await
        .unwrap();
    let fetched = KitchenSinkSqlRepository::get(&mut conn, id).await.unwrap();

    assert_eq!(fetched.id, row.id);
    assert_eq!(fetched.name, row.name);
    assert_eq!(fetched.note, row.note);
    assert_eq!(fetched.count, row.count);
    assert_eq!(fetched.ratio, row.ratio);
    assert_eq!(fetched.flag, row.flag);
    assert_eq!(fetched.tags.0, row.tags.0);
    assert_eq!(fetched.deleted, false);
}

#[tokio::test]
async fn list_returns_inserted_rows() {
    let pool = setup_pool().await;
    let mut conn = pool.acquire().await.unwrap();

    let row = sample("listed");
    let id = row.id;
    KitchenSinkSqlRepository::insert(&mut conn, &row)
        .await
        .unwrap();

    let rows = KitchenSinkSqlRepository::list(
        &mut conn,
        ListQuery {
            count: 10,
            offset: 0,
        },
    )
    .await
    .unwrap();

    assert_eq!(rows.len(), 1);
    assert_eq!(rows[0].id, id);
}

#[tokio::test]
async fn update_changes_named_column() {
    let pool = setup_pool().await;
    let mut conn = pool.acquire().await.unwrap();

    let row = sample("before");
    let id = row.id;
    KitchenSinkSqlRepository::insert(&mut conn, &row)
        .await
        .unwrap();

    KitchenSinkSqlRepository::update(
        &mut conn,
        id,
        vec![UpdateColumnOp {
            column: "name".into(),
            value: UpdateValue::Text("after".into()),
        }],
    )
    .await
    .unwrap();

    let fetched = KitchenSinkSqlRepository::get(&mut conn, id).await.unwrap();
    assert_eq!(fetched.name, "after");
}

#[tokio::test]
async fn delete_marks_deleted_flag() {
    let pool = setup_pool().await;
    let mut conn = pool.acquire().await.unwrap();

    let row = sample("to_delete");
    let id = row.id;
    KitchenSinkSqlRepository::insert(&mut conn, &row)
        .await
        .unwrap();

    KitchenSinkSqlRepository::delete(&mut conn, id)
        .await
        .unwrap();

    let fetched = KitchenSinkSqlRepository::get(&mut conn, id).await.unwrap();
    assert_eq!(fetched.deleted, true);
}

#[tokio::test]
async fn restore_unmarks_deleted_flag() {
    let pool = setup_pool().await;
    let mut conn = pool.acquire().await.unwrap();

    let row = sample("to_restore");
    let id = row.id;
    KitchenSinkSqlRepository::insert(&mut conn, &row)
        .await
        .unwrap();
    KitchenSinkSqlRepository::delete(&mut conn, id)
        .await
        .unwrap();

    KitchenSinkSqlRepository::restore(&mut conn, id)
        .await
        .unwrap();

    let fetched = KitchenSinkSqlRepository::get(&mut conn, id).await.unwrap();
    assert_eq!(fetched.deleted, false);
}

// ----- Journal apply -----

#[tokio::test]
async fn apply_journal_with_duplicate_create_is_idempotent() {
    let db = setup_database().await;
    let row = sample("dup");
    let id = row.id;

    db.insert::<KitchenSinkSqlRepository>(&row).await.unwrap();

    let op = row.op_create().unwrap();
    let entry = JournalEntry::new("kitchen_sinks", &op);

    let journal_id = db
        .apply_journal::<KitchenSinkSqlRepository>(entry)
        .await
        .unwrap();

    let keys = db.get_journal_keys().unwrap();
    assert!(keys.contains(journal_id.as_bytes()));

    let fetched = db.get::<KitchenSinkSqlRepository>(id).await.unwrap();
    assert_eq!(fetched.name, row.name);
}

#[tokio::test]
async fn apply_journals_batch_applies_all_entries() {
    let db = setup_database().await;

    let row1 = sample("one");
    let row2 = sample("two");
    let id1 = row1.id;
    let id2 = row2.id;

    let entry1 = JournalEntry::new("kitchen_sinks", &row1.op_create().unwrap())
        .to_bytes()
        .unwrap();
    let entry2 = JournalEntry::new("kitchen_sinks", &row2.op_create().unwrap())
        .to_bytes()
        .unwrap();

    let journal_ids = RepositoryRegistry::instance()
        .apply_journals_bytes(&db, &[entry1.as_slice(), entry2.as_slice()])
        .await
        .unwrap();

    assert_eq!(journal_ids.len(), 2);

    let keys = db.get_journal_keys().unwrap();
    assert!(keys.contains(&journal_ids[0].as_bytes()));
    assert!(keys.contains(&journal_ids[1].as_bytes()));

    let fetched1 = db.get::<KitchenSinkSqlRepository>(id1).await.unwrap();
    assert_eq!(fetched1.name, row1.name);
    let fetched2 = db.get::<KitchenSinkSqlRepository>(id2).await.unwrap();
    assert_eq!(fetched2.name, row2.name);
}
