[application]
asset_dir = "assets"
default_platform = "mobile"
name = "dsot_mobile"

[web.app]
title = "dsot_mobile_app"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

[bundle]
identifier = "com.dpires.dsot"
publisher = "dpires"
icon = [
    "assets/imgs/icon_256.png",
    "assets/imgs/icon.ico",
    "assets/imgs/icon_256.icns",
    "assets/imgs/icon.icns",
]
