-- Your SQL goes here
CREATE TABLE IF NOT EXISTS files (
    id BLOB NOT NULL PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tags (
    id BLOB NOT NULL PRIMARY KEY,
    name TEXT NOT NULL
);

-- 019148d2-2bc2-7000-b000-000000000001

CREATE TABLE IF NOT EXISTS tag_values (
    id BLOB NOT NULL PRIMARY KEY,
    tag_id BLOB NOT NULL REFERENCES tags(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS file_tags (
    file_id BLOB NOT NULL REFERENCES files(id) ON DELETE CASCADE,
    tag_value_id BLOB NOT NULL REFERENCES tag_value(id) ON DELETE CASCADE
);
